const drinks = [{
    "idDrink": "11007",
    "strDrink": "Margarita",
    "strDrinkAlternate": null,
    "strDrinkES": null,
    "strDrinkDE": null,
    "strDrinkFR": null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    "strTags": "IBA,ContemporaryClassic",
    "strVideo": null,
    "strCategory": "Ordinary Drink",
    "strIBA": "Contemporary Classics",
    "strAlcoholic": "Alcoholic",
    "strGlass": "Cocktail glass",
    "strInstructions": "Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.",
    "strInstructionsES": null,
    "strInstructionsDE": "Reiben Sie den Rand des Glases mit der Limettenscheibe, damit das Salz daran haftet. Achten Sie darauf, dass nur der äußere Rand angefeuchtet wird und streuen Sie das Salz darauf. Das Salz sollte sich auf den Lippen des Genießers befinden und niemals in den Cocktail einmischen. Die anderen Zutaten mit Eis schütteln und vorsichtig in das Glas geben.",
    "strInstructionsFR": null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/wpxpvu1439905379.jpg",
    "strIngredient1": "Tequila",
    "strIngredient2": "Triple sec",
    "strIngredient3": "Lime juice",
    "strIngredient4": "Salt",
    "strMeasure1": "1 1/2 oz ",
    "strMeasure2": "1/2 oz ",
    "strMeasure3": "1 oz ",
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2015-08-18 14:42:59"
},
{
    "idDrink": "11000",
    "strDrink": "Mojito",
    "strDrinkAlternate": null,
    "strDrinkES": null,
    "strDrinkDE": null,
    "strDrinkFR": null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    "strTags": "IBA,ContemporaryClassic,Alcoholic,USA,Christmas",
    "strVideo": null,
    "strCategory": "Cocktail",
    "strIBA": "Contemporary Classics",
    "strAlcoholic": "Alcoholic",
    "strGlass": "Highball glass",
    "strInstructions": "Muddle mint leaves with sugar and lime juice. Add a splash of soda water and fill the glass with cracked ice. Pour the rum and top with soda water. Garnish and serve with straw.",
    "strInstructionsES": null,
    "strInstructionsDE": "Minzblätter mit Zucker und Limettensaft verrühren. Füge einen Spritzer Sodawasser hinzu und fülle das Glas mit gebrochenem Eis. Den Rum eingießen und mit Sodawasser übergießen. Garnieren und mit einem Strohhalm servieren.",
    "strInstructionsFR": null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/rxtqps1478251029.jpg",
    "strIngredient1": "Light rum",
    "strIngredient2": "Lime",
    "strIngredient3": "Sugar",
    "strIngredient4": "Mint",
    "strIngredient5": "Soda water",
    "strMeasure1": "2-3 oz ",
    "strMeasure2": "Juice of 1 ",
    "strMeasure3": "2 tsp ",
    "strMeasure4": "2-4 ",
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2016-11-04 09:17:09"
},
{
    "idDrink": "17207",
    "strDrink": "Pina Colada",
    "strDrinkAlternate": null,
    "strDrinkES": null,
    "strDrinkDE": null,
    "strDrinkFR": null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    "strTags": "IBA,ContemporaryClassic",
    "strVideo": null,
    "strCategory": "Ordinary Drink",
    "strIBA": "Contemporary Classics",
    "strAlcoholic": "Alcoholic",
    "strGlass": "Collins glass",
    "strInstructions": "Mix with crushed ice in blender until smooth. Pour into chilled glass, garnish and serve.",
    "strInstructionsES": null,
    "strInstructionsDE": "Mit zerstoßenem Eis im Mixer mischen, bis es glatt ist. In ein gekühltes Glas geben, garnieren und servieren.",
    "strInstructionsFR": null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/cpf4j51504371346.jpg",
    "strIngredient1": "Light rum",
    "strIngredient2": "Coconut milk",
    "strIngredient3": "Pineapple",
    "strMeasure1": "3 oz ",
    "strMeasure2": "3 tblsp ",
    "strMeasure3": "3 tblsp ",
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2017-09-02 17:55:46"
},
{
    "idDrink": "11009",
    "strDrink": "Moscow Mule",
    "strDrinkAlternate": null,
    "strDrinkES": null,
    "strDrinkDE": null,
    "strDrinkFR": null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    "strTags": "IBA,ContemporaryClassic",
    "strVideo": null,
    "strCategory": "Punch / Party Drink",
    "strIBA": "Contemporary Classics",
    "strAlcoholic": "Alcoholic",
    "strGlass": "Copper Mug",
    "strInstructions": "Combine vodka and ginger beer in a highball glass filled with ice. Add lime juice. Stir gently. Garnish.",
    "strInstructionsES": null,
    "strInstructionsDE": "Mischen Sie Wodka und Ingwerbier in einem mit Eis gefüllten Highball-Glas. Limettensaft hinzufügen. Vorsichtig umrühren. Garnieren.",
    "strInstructionsFR": null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/3pylqc1504370988.jpg",
    "strIngredient1": "Vodka",
    "strIngredient2": "Lime juice",
    "strIngredient3": "Ginger ale",
    "strMeasure1": "2 oz ",
    "strMeasure2": "2 oz ",
    "strMeasure3": "8 oz ",
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2017-09-02 17:49:48"
}
];

export default drinks;